"""Initial revision

Revision ID: 03aa04e83686
Revises: 
Create Date: 2025-07-27 01:03:29.171596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03aa04e83686'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('TelegramId', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_table('pass_and_ques',
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('PassHash', sa.TEXT(), nullable=True),
    sa.Column('QuestionAnswerHash', sa.TEXT(), nullable=True),
    sa.Column('Question', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_table('users_groups_and_channels',
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('ChatId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('ChatId')
    )
    op.create_table('posts',
    sa.Column('PostId', sa.UUID(), nullable=False),
    sa.Column('ChatId', sa.INTEGER(), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('PostText', sa.TEXT(), nullable=True),
    sa.Column('ReactionListString', sa.TEXT(), nullable=True),
    sa.Column('PhotosIdListString', sa.TEXT(), nullable=True),
    sa.Column('TimeToPost', sa.DATE(), nullable=True),
    sa.Column('PostStatus', sa.Enum('Planning', 'Posted', name='poststatusesenum'), nullable=True),
    sa.ForeignKeyConstraint(['ChatId'], ['users_groups_and_channels.ChatId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('PostId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users_groups_and_channels')
    op.drop_table('pass_and_ques')
    op.drop_table('users')
    # ### end Alembic commands ###
