"""Initial revision

Revision ID: a73260b36f83
Revises: 03aa04e83686
Create Date: 2025-07-27 12:51:48.100528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73260b36f83'
down_revision: Union[str, Sequence[str], None] = '03aa04e83686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('Active', sa.BOOLEAN(), nullable=False),
    sa.Column('ExprireTime', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('UserId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
